let
    Source = Value.NativeQuery(PostgreSQL.Database("localhost", "item_master"), "SELECT#(lf)    pi.*, (pi.expiration_date - INTERVAL '365 days')::date AS short_dating_date,#(lf)#(lf)    CASE#(lf)        WHEN pi.expiration_date < CURRENT_DATE THEN 'Expired'#(lf)#(lf)        WHEN pi.expiration_date <= CURRENT_DATE + INTERVAL '365 days'#(lf)           THEN 'Short Dated'#(lf)#(lf)        WHEN (pi.expiration_date - INTERVAL '365 days')#(lf)             BETWEEN CURRENT_DATE#(lf)             AND (CURRENT_DATE + INTERVAL '3 months')#(lf)            THEN '1-3 Months'#(lf)#(lf)        WHEN (pi.expiration_date - INTERVAL '365 days')#(lf)             > (CURRENT_DATE + INTERVAL '3 months')#(lf)         AND (pi.expiration_date - INTERVAL '365 days')#(lf)             <= (CURRENT_DATE + INTERVAL '6 months')#(lf)            THEN '4-6 Months'#(lf)#(lf)        WHEN (pi.expiration_date - INTERVAL '365 days')#(lf)             > (CURRENT_DATE + INTERVAL '6 months')#(lf)         AND (pi.expiration_date - INTERVAL '365 days')#(lf)             <= (CURRENT_DATE + INTERVAL '12 months')#(lf)            THEN '7-12 Months'#(lf)#(lf)        ELSE 'Over 12 Months'#(lf)    END AS short_dating_timeframe, pc.cost as sku_cost#(lf)#(lf)FROM #(lf)#(tab)sku.physical_inventory pi#(lf)LEFT JOIN#(lf)#(tab)sku.product_costs pc#(lf)ON#(lf)#(tab)pi.sku = pc.sku#(lf)", null, [EnableFolding=true]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"sku_cost", Currency.Type}}),
    #"Added Custom" = Table.AddColumn(#"Changed Type", "short_date_risk", each if([short_dating_timeframe] = "Over 12 Months") then "Not At Risk" else "At Risk"),
    #"Filtered Rows" = Table.SelectRows(#"Added Custom", each true)
in
    #"Filtered Rows"
